apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpf-test
  namespace: default
  labels:
    app: wpf-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wpf-test
  template:
    metadata:
      labels:
        app: wpf-test
    spec:
      imagePullSecrets:
        - name: default-secret
      containers:
      - name: httpserver
        image: "{IMAGE}"
        ports:
        - containerPort: 80