apiVersion: v1
kind: Service
metadata:
  name: wpf-test-node
  namespace: default
spec:
  selector:
    app: wpf-test
  ports:
    - name: service-0
      targetPort: 80
      port: 80
      nodePort: 30010
      protocol: TCP
  type: NodePort