name: github action is cce demo
on:
  push:
    branches: [ master ]

jobs:
  buildImageInSwrAndDeployCCE:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login --username=${{ secrets.SWR_USER }} swr.cn-north-4.myhuaweicloud.com --password=${{ secrets.SWR_PASS }}
        cd ./httpserver && docker build . --file Dockerfile --tag swr.cn-north-4.myhuaweicloud.com/panbuhei/cce-test:${{ github.sha }}
        docker push swr.cn-north-4.myhuaweicloud.com/panbuhei/cce-test:${{ github.sha }}

    # 更改deployment/yml中的镜像，{IMAGE}是预留的
    - run: |
        sed -i 's/{IMAGE}/swr.cn-north-4.myhuaweicloud.com/panbuhei/cce-test:${{ github.sha }}/g' ./deploy/deployment.yml

    - name: Deploy to cluster
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        # BASE64-encoded kubeconfig
        config:  ${{ secrets.KUBE_CONFIG }}
        # kubectl version (1.18, 1.19, 1.20, 1.21, latest)
        version: 1.21
        args: 'apply -f ./deploy/deployment.yml'
    - name: svc to cluster
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config:  ${{ secrets.KUBE_CONFIG }}
        version: 1.21
        args: 'apply -f ./deploy/service.yml'
    - name: Verify deployment
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG }}
        version: 1.21
        args: rollout status deployment/wpf-test