name: github action is cce demo
on:
  push:
    branches: [ master ]

jobs:
  buildImageInSwrAndDeployCCE:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login --username=${{ secrets.SWR_USER }} swr.cn-north-4.myhuaweicloud.com --password=${{ secrets.SWR_PASS }}
        cd ./httpserver && docker build . --file Dockerfile --tag swr.cn-north-4.myhuaweicloud.com/panbuhei/cce-test:${{ github.sha }}
        docker push swr.cn-north-4.myhuaweicloud.com/panbuhei/cce-test:${{ github.sha }}
    # k8s部署
    - run: |
        sed -i 's/{TAG}/${{ github.sha }}/g' ./deploy/deployment.yml

    - name: deploy k8s 
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        KUBECTL_VERSION: "1.23"
    - name: connect k8s
      run: |
        kubectl config use-context external
    - name: deployment
      run: |
        kubectl apply -f ./deploy/deployment.yml
    - name: service
      run: |
        kubectl apply -f ./deploy/service.yml
