name: github action is cce demo
on:
  push:
    branches: [ master ]

jobs:
  buildImageInSwrAndDeployCCE:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login --username=${{ secrets.SWR_USER }} swr.cn-north-4.myhuaweicloud.com --password=${{ secrets.SWR_PASS }}
        cd ./httpserver && docker build . --file Dockerfile --tag swr.cn-north-4.myhuaweicloud.com/panbuhei/cce-test:${{ github.sha }}
        docker push swr.cn-north-4.myhuaweicloud.com/panbuhei/cce-test:${{ github.sha }}
    # k8s部署
    - run: |
        sed -i 's/{TAG}/${{ github.sha }}/g' ./deploy/deployment.yml

    - name: kubectl-simple
      # You may pin to the exact commit or the version.
      # uses: steebchen/kubectl@7c4c70d551952e40881998b840e16d4d9824a54f
      uses: steebchen/kubectl@v2.1.1
      with:
        # kubectl version, e.g. `v1.21.0`, defaults to latest
        version: v1.21.0
        # kube config data
        config: ${{ secrets.KUBE_CONFIG }}
        # kubectl command to run, without the kubectl, e.g. `get pods`
        command: cluster-info
        # Url to download the binaries from, defaults to the official dl.k8s.io url
        binaries-url: # optional
